# Generated by Django 4.2.15 on 2024-10-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_published_alter_blogpost_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
    ]
